---
name: Dependency Review

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
    uses:
      ministryofjustice/data-engineering-github-actions/.github/workflows/reusable-dependency-review.yml@a069b8db6abf405bbdc97e045ec9b47376aabc23  # v1.1.1
