---
name: Dependency Review

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
    uses:
      ministryofjustice/data-engineering-github-actions/.github/workflows/reusable-dependency-review.yml@f5f397ce2bdfed91903077270fc9cb0ff8e90435  # v1.2.0
