---
name: Run lambda tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Lambda Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install dependencies
        run: |
          uv venv
          uv pip install .
      - name: Run tests
        run: |
          if [ -d tests ]; then uv run -m pytest -vv tests; fi
