---
name: Run lambda tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Lambda Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install dependencies
        run: |
          uv venv
          uv pip install .
      - name: Run tests
        run: |
          if [ -d tests ]; then uv run -m pytest -vv tests; fi
