---
name: List Open Prs
permissions:
  contents: read
  pull-requests: read
on:
  schedule:
    - cron: 0 7 * * 1-5
  workflow_dispatch:
jobs:
  list-open-prs:
    name: List Open PRs
    uses:
      ministryofjustice/data-engineering-github-actions/.github/workflows/reusable-list-open-prs.yml@a069b8db6abf405bbdc97e045ec9b47376aabc23  # v1.1.1
    with:
      dry_run:
        ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true' || false }}
    secrets:
      slack_workflow_url: ${{ secrets.SLACK_WEBHOOK_URL }}
