---
name: List Open Prs
on:
  schedule:
    - cron: 0 7 * * 1-5
  workflow_dispatch:
jobs:
  list-open-prs:
    name: List Open PRs
    uses:
      ministryofjustice/data-engineering-github-actions/.github/workflows/reusable-list-open-prs.yml@bc3387b3bdd728d1c7e26e7f576929e4957507be  # v1.1.0
    with:
      dry_run:
        ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true' || false }}
    secrets:
      slack_workflow_url: ${{ secrets.SLACK_WEBHOOK_URL }}
