---
name: Check pre commit
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
jobs:
  pre-commit:
    name: Check pre commit
    permissions:
      contents: read
    uses:
      ministryofjustice/data-engineering-github-actions/.github/workflows/reusable-pre-commit.yml@a069b8db6abf405bbdc97e045ec9b47376aabc23  # v1.1.1
    with:
      include_terraform: true
