---
name: Security
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
jobs:
  security:
    name: Security
    permissions:
      security-events: write
      contents: read
      actions: read
    uses:
      ministryofjustice/data-engineering-github-actions/.github/workflows/reusable-security.yml@f5f397ce2bdfed91903077270fc9cb0ff8e90435  # v1.2.0
