---
name: Security
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
jobs:
  security:
    name: Security
    permissions:
      security-events: write
      contents: read
      actions: read
    uses:
      ministryofjustice/data-engineering-github-actions/.github/workflows/reusable-security.yml@a069b8db6abf405bbdc97e045ec9b47376aabc23  # v1.1.1
